"""add_commission_system

Revision ID: 2766adcc2c7a
Revises: b2e4f9e4c10e
Create Date: 2026-04-27 13:34:56.751885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2766adcc2c7a'
down_revision: Union[str, None] = 'b2e4f9e4c10e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_settings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('commission_enabled', sa.Boolean(), nullable=True),
    sa.Column('default_commission_percent', sa.Float(), nullable=True),
    sa.Column('freelancer_commission_percent', sa.Float(), nullable=True),
    sa.Column('store_commission_percent', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('transactions', sa.Column('gross_amount', sa.Float(), nullable=True))
    op.add_column('transactions', sa.Column('commission_percent', sa.Float(), nullable=True))
    op.add_column('transactions', sa.Column('commission_amount', sa.Float(), nullable=True))
    op.add_column('transactions', sa.Column('seller_payout_amount', sa.Float(), nullable=True))
    op.add_column('transactions', sa.Column('net_amount', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'net_amount')
    op.drop_column('transactions', 'seller_payout_amount')
    op.drop_column('transactions', 'commission_amount')
    op.drop_column('transactions', 'commission_percent')
    op.drop_column('transactions', 'gross_amount')
    op.drop_table('platform_settings')
    # ### end Alembic commands ###
