"""phase_5_disputes_approvals

Revision ID: 7bcd42d07259
Revises: 2766adcc2c7a
Create Date: 2026-04-27 14:00:12.741708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bcd42d07259'
down_revision: Union[str, None] = '2766adcc2c7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disputes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('client_id', sa.String(), nullable=False),
    sa.Column('freelancer_id', sa.String(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('open', 'under_review', 'resolved_client', 'resolved_freelancer', 'closed', name='disputestatus'), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('resolved_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['freelancer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['admins.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('reviews', sa.Column('verified_purchase', sa.Boolean(), nullable=True))
    op.add_column('reviews', sa.Column('is_public', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_approved', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_approved')
    op.drop_column('reviews', 'is_public')
    op.drop_column('reviews', 'verified_purchase')
    op.drop_table('disputes')
    # ### end Alembic commands ###
