"""phase_1_upgrades

Revision ID: b2e4f9e4c10e
Revises: 0002_security_columns
Create Date: 2026-04-27 13:07:03.078643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b2e4f9e4c10e'
down_revision: Union[str, None] = '0002_security_columns'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE availabilitystatus AS ENUM ('available', 'busy', 'offline');")
    op.execute("ALTER TYPE userrole ADD VALUE IF NOT EXISTS 'store_owner';")
    
    op.create_table('feedbacks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('type', sa.Enum('suggestion', 'bug', 'feature', name='feedbacktype'), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tickets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('open', 'pending', 'resolved', 'closed', name='ticketstatus'), nullable=True),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', name='ticketpriority'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ticket_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ticket_id', sa.String(), nullable=False),
    sa.Column('sender_id', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorites',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('target_freelancer_id', sa.String(), nullable=True),
    sa.Column('product_id', sa.String(), nullable=True),
    sa.Column('task_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['target_freelancer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('reviewer_id', sa.String(), nullable=False),
    sa.Column('freelancer_id', sa.String(), nullable=True),
    sa.Column('product_id', sa.String(), nullable=True),
    sa.Column('store_id', sa.String(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['freelancer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_applications_freelancer_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_task_id'), table_name='applications')
    op.drop_index(op.f('ix_conversations_client_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_participant_id'), table_name='conversations')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_sender_id'), table_name='messages')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.add_column('products', sa.Column('stock', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_tasks_created_at'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_creator_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.add_column('transactions', sa.Column('razorpay_order_id', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('razorpay_payment_id', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('razorpay_signature', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('transaction_metadata', sa.JSON(), nullable=True))
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_column('transactions', 'stripe_payment_intent_id')
    op.drop_column('transactions', 'metadata')
    op.add_column('users', sa.Column('hourly_rate', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('availability', sa.Enum('available', 'busy', 'offline', name='availabilitystatus'), nullable=True))
    op.add_column('users', sa.Column('last_seen', sa.DateTime(), nullable=True))
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_index(op.f('ix_users_is_banned'), table_name='users')
    op.drop_index(op.f('ix_users_registration_ip'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_unique_constraint(None, 'users', ['username'])
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'registration_ip')
    op.drop_column('users', 'last_login_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_login_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('registration_ip', sa.VARCHAR(length=45), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('locked_until', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_index(op.f('ix_users_registration_ip'), 'users', ['registration_ip'], unique=False)
    op.create_index(op.f('ix_users_is_banned'), 'users', ['is_banned'], unique=False)
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.drop_column('users', 'last_seen')
    op.drop_column('users', 'availability')
    op.drop_column('users', 'hourly_rate')
    op.add_column('transactions', sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('transactions', sa.Column('stripe_payment_intent_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    op.drop_column('transactions', 'transaction_metadata')
    op.drop_column('transactions', 'razorpay_signature')
    op.drop_column('transactions', 'razorpay_payment_id')
    op.drop_column('transactions', 'razorpay_order_id')
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('ix_tasks_creator_id'), 'tasks', ['creator_id'], unique=False)
    op.create_index(op.f('ix_tasks_created_at'), 'tasks', ['created_at'], unique=False)
    op.drop_column('products', 'stock')
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index(op.f('ix_messages_sender_id'), 'messages', ['sender_id'], unique=False)
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_conversations_participant_id'), 'conversations', ['participant_id'], unique=False)
    op.create_index(op.f('ix_conversations_client_id'), 'conversations', ['client_id'], unique=False)
    op.create_index(op.f('ix_applications_task_id'), 'applications', ['task_id'], unique=False)
    op.create_index(op.f('ix_applications_freelancer_id'), 'applications', ['freelancer_id'], unique=False)
    op.drop_table('reviews')
    op.drop_table('favorites')
    op.drop_table('ticket_messages')
    op.drop_table('tickets')
    op.drop_table('feedbacks')
    
    op.execute("DROP TYPE availabilitystatus;")
    # ### end Alembic commands ###
